Algoritmo "semnome"

Var

   salario: real
   salario_minimo: real
   quantidade_salarios: real
   
   
Inicio
      //ENTRADA
      escreva("Digite o valor do salario: ")
      leia(salario)
      //PROCESSAMENTO
      salario_minimo <-1621
      quantidade_salarios <- salario /salario_minimo
      
      //SAIDA
      escreval("Quantidade de salario: ", quantidade_salarios:3:1)
      
      





      
      
      

Fimalgoritmo