Algoritmo "semnome"

Var

   numero: inteiro
   antecessor: inteiro
   sucessor: inteiro
   pedir: inteiro
   
   
Inicio

      escreval("Digite um numero")
      leia(numero)
      
      antecessor <- numero -1
      
      sucessor <- numero +1
      
      //SAIDA
      
      escreval("antecessor ", antecessor)
      
      escreval("sucessor ", sucessor)

Fimalgoritmo